apiVersion: apps/v1
kind: Deployment
metadata:
  name: scripts-server
  namespace: alsabagtv
  labels:
    app: scripts-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scripts-server
  template:
    metadata:
      labels:
        app: scripts-server
    spec:
      containers:
        - name: scripts-server
          image: docker.io/howcansheslap/scripts-server:1.0.0
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: scripts-server
  namespace: alsabagtv
spec:
  selector:
    app: scripts-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: scripts-server-ingress
  namespace: alsabagtv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - alsabagtv-scripts.alsabagtech.com
      secretName: tls-secret
  rules:
    - host: alsabagtv-scripts.alsabagtech.com
      http:
        paths:
          - backend:
              serviceName: scripts-server
              servicePort: 80
            path: /(.*)
